### ISSUE TITLE
return `Cache` not `*cache` 

### ISSUE THREAD

**Issue by VineyAT** [3FanYu/go-practice-localcache#1]
https://github.com/3FanYu/go-practice-localcache/blob/3033867638f575923e2a7f7d9f136a57ae0c2e76/impl.go#L25

func New() `Cache` { ... }

應該是要回傳 interface 而不是實作

**Comment by 3FanYu** [comment]
okay [done](https://github.com/3FanYu/go-practice-localcache/commit/6a6e8339727d67f03c1c5dd38bf91fbc41cd0e88)
