### ISSUE TITLE
scope incorrect

### ISSUE THREAD

**Issue by VineyAT** [3FanYu/go-practice-localcache#2]
https://github.com/3FanYu/go-practice-localcache/blob/3033867638f575923e2a7f7d9f136a57ae0c2e76/impl.go#L10

應該封裝在 type `cache` struct 當中，你寫在 var 裡面就是一個全域變數了，所有 New() 出來的都受到影響

**Comment by 3FanYu** [comment]
okay [fixed](https://github.com/3FanYu/go-practice-localcache/commit/04d6286901695b1e445b6aa59f54285b4a4baa10)
