### ISSUE TITLE
handle cache miss

### ISSUE THREAD

**Issue by VineyAT** [3FanYu/go-practice-localcache#3]
https://github.com/3FanYu/go-practice-localcache/blob/3033867638f575923e2a7f7d9f136a57ae0c2e76/impl.go#L50

need to take care of cases the data didn't exist in the cache, and return error

**Comment by 3FanYu** [comment]
okay [done](https://github.com/3FanYu/go-practice-localcache/commit/f1f4d562d4831fb736dc1c4ad794aa93309e7a9a)
