### ISSUE TITLE
Comments?

### ISSUE THREAD

**Issue by VineyAT** [3FanYu/go-practice-localcache#4]
https://github.com/3FanYu/go-practice-localcache/blob/3033867638f575923e2a7f7d9f136a57ae0c2e76/cache.go#L3

所有的 public 都要寫註解，看起來都沒有寫

**Comment by 3FanYu** [comment]
okay [done](https://github.com/3FanYu/go-practice-localcache/commit/ecd30534b882a683668c557ba156f06057e57709)

**Comment by VineyAT** [comment]
It's better to start with `Cache`. But it's ok to see the comment.
