### ISSUE TITLE
Why singleton?

### ISSUE THREAD

**Issue by VineyAT** [3FanYu/go-practice-localcache#5]
https://github.com/3FanYu/go-practice-localcache/blob/3033867638f575923e2a7f7d9f136a57ae0c2e76/impl.go#L9

假使介面要設計 New 建議就不要用 singleton 回傳，反之，假使要用 singleton，應該是寫成一個 static method，而不要透過 New，建議這個練習可以移除掉 singleton

**Comment by 3FanYu** [comment]
okay [done](https://github.com/3FanYu/go-practice-localcache/commit/04d6286901695b1e445b6aa59f54285b4a4baa10)
